version: '3.1'
services:
    coredns:
        image: coredns/coredns
        container_name: coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './config:/root/'
        command: -conf /root/Corefile